# Lando configuration file.
#
# From https://docs.platform.sh/development/local/lando.html

# Name the application the same as in your .platform.app.yaml.
name: manifesto

# Use the recipe appropriate for your application.
recipe: drupal8

config:
  # Lando defaults to Apache. Switch to nginx to match Platform.sh.
  via: nginx

  # Set the webroot to match your .platform.app.yaml.
  webroot: web

  # Let's use PHP 7.3.
  php: '7.3'

  # Enable XDebug.
  xdebug: true

services:
  appserver:
    build:
      # Automatically composer install before the app starts.
      - composer install
  # Override some MySQL settings - in particular, max_allowed_packet.
  database:
    # Lando defaults to the latest MySQL release, but Platform.sh uses MariaDB.
    # Specify the version to match what's in services.yaml.
    type: mariadb:10.2
    # The following lines show how you can use a custom MariaDB image.
#    type: mariadb:custom
#      overrides:
#        services:
#          image: drupaldocker/mariadb:10.2
    config:
    database: .lando-config/my.cnf
